# Abstract {-}

약동학 지표를 구할 시 활용되는 비구획 분석을 R pacakge에서 적용하여 테오필린(Theophylline)과 인도메타신(Indomethacin) 데이터에 대한 분석을 실시하였다. 
각각의 데이터에 대해 Edison 엡 내에서 농도-시간 곡선에 대한 그래프를 다양한 방식으로 구현할 수 있었으며, 계획한 R script를 통해 도출된 결과에서도 현재 임상적으로 가장 널리 쓰이는 비구획 분석방법 소프트웨어와 동일한 값임을 확인하였다. 
또한 실제 비구획 분석보다 한 단계 더 복잡한 분석에 대해서도 실제 구현 가능함을 확인하였다. 
이를 통해 앞으로 다양한 약동학적 분석방법을 Edison system 안에서 구현하고 활용할 수 있을 것으로 기대된다.
 
# 서론 {#introduction}

신체에서 약물이 들어올 때, 약물의 양과 효과는 관련성이 있으며, 따라서 약물의 효과를 파악하기 위해 우리 몸에서 약물이 가지는 약동학적 특성을 파악하는 것은 굉장히 중요하다. 다양한 신약 개발 과정에서 이러한 약동학적 특성을 파악하여, 약물의 개발을 지속하거나 중지하기도 하며, 마취통증의학과나 내과 등의 다양한 임상 의학에서도 신체에 중요 영향을 미칠 수 있는 약물에 대하여 대략적인 농도를 파악하기 위해 약물의 약동학적 특성을 이용한다. 이러한 약동학적 약물의 특성은 간단하게 ADME라는 용어로 설명할 수 있는데 이는 absorption (흡수), distribution(분포), metabolism(대사), excretion(배설)을 의미한다. 약물이 다양한 경로 (경구제 복용, 피하 주사, 정맥 주사, 근육 주사 등)를 통해 우리 몸에 들어오게 되면, 정맥주사 이외의 나머지는 흡수(absorption)의 과정을 거쳐 우리 몸의 정맥에 분포하게 되며, 이러한 약물은 분포(distribution)와 제거(metabolism) 과정에서 감소하게 되고, 제거 과정은 우리 몸에 투여된 물질이 여러 기관(organ)을 통해서 다른 물질로 변하여(metabolism) 제거되거나 물질이 변화하지 않고 그대로 배설(excretion) 되는 과정으로 진행되게 된다. 이러한 수치들은 각각 약물의 농도가 증가하고 감소하는 과정과 밀접하게 연관되어 있으며, 이러한 과정들을 정량화하여 식을 세울 수 있다면, 약물을 투여한 이후의 농도를 보다 정확하게 예측할 수 있다. 
이 때 흡수와 관련된 지표로는 흡수속도 상수(absorption rate constant)와 생체이용률(bioavailability), 분포, 제거와 관련된 지표로는 분포용적(Volume of distribution)과 청소율(Clearance)을 이용하게 되며, 다음 값들을 정확하게 예측하는 것이 약동학 분야에서의 핵심 중의 하나라고 볼 수 있다.
이러한 지표들을 구하기 위해서 현재 여러가지 방법들을 사용하고 있으며, 그 중 가장 간단하고도 널리 쓰이는 방법은 비구획분석(Non-compartmental analysis, NCA)으로  FDA(Food and Drug Administration)에서도 다음의 방식으로 약동학적 지표를 구하는 것을 허용하고 있다.
따라서 이번 Edison system을 통하여 주어진 시간과 농도로부터 비구획 분석 방법을 사용하여 약동학적 주요 지표를 직접 구해보고자 한다.

# 이론 및 계산 방법 {#method}

비구획 분석이란 시간, 농도가 표현되어 있는 곡선에서 아무런 가정을 하지 않고 분석하는 것을 의미한다. 이때 다음과 같은 가정을 통해서 최대농도(Cmax) 및 최대농도에 도달하는 시간(Tmax), 전체 시간-농도 곡선의 면적(Area under the time-concentration curve, AUC)등을 구하게 된다. 이를 통해 측정된 지표들을 통하여 약물의 특성을 파악하고 특정구간에서의 농도를 예측하게 된다. 
비구획 분석에서는 기본적으로 statistical moment theory (단순히 하나의 분자가 우리 몸에 들어와서 제거되지 까지는 예측하는 것이 힘들지만 그 개개의 분자들의 양이 늘어날수록 그들의 전반적인 행동이 규칙적으로 이루어진다는 이론)를 가정하고 이를 통해 우리는 각각의 분자가 우리 몸에서 얼마나 머무는지에 대한 평균값을 예상할 수 있게 된다. 이 시간을 MRT(mean residence time)이라고 지칭하게 되며, 이것은 농도와 시간의 곱을 적분한 값에서 단순 농도 값을 적분한 농도를 나누어 준 값으로 다음과 같이 표현해 줄 수 있다. 
 
이때 식에서 표현된 AUMC는 area under the first moment curve로 농도와 시간의 곱을 시간에 대해서 적분한 값에 해당하며 AUC는 area under concentration으로 농도를 시간에 대해 적분한 값에 해당한다. 
하지만 이 때, 각각의 약물에서 농도와 시간 사이의 명확한 함수관계를 확인할 수 없고, 주어진 정보도 제한적이므로 농도를 시간으로 적분하기에는 상당한 어려움이 따른다. 따라서 이를 간소화 하기 위해 Linear trapezoidal method(농도-시간 곡선에서 농도를 측정한 점과 점 사이의 면적을 사다리꼴이라 가정하고 넓이를 구하는 방식)를 사용하게 된다. 처음 농도를 측정한 부분부터 마지막 샘플까지를 t1,t2 …tlast로 표현했을 시 t1과 t2의 사이의 AUC와 AUMC는 다음과 같이 계산된다
 
 이 방식을 계속 이용하여 각각의 구간 값의 합을 모두 더한 값으로 AUClast(처음 농도를 측정하기 시작한 구간부터 마지막 농도를 측정한 구간까지 linear trapezoidal method를 통해서 값을 계산한 방식), AUMClast(처음 농도를 측정하기 시작한 구간부터 마지막 농도를 측정한 구간까지 linear trapezoidal method를 통해서 값을 계산한 방식)를 측정해 주게 된다.
 
Figure 1 Linear trapezoidal method
추가적으로 마지막으로 농도를 잰 시점에서 모든 약물이 우리 몸에서 빠져나가는 시점까지의 값을 구하기 위해서 마지막으로 측정한 점의 기울기가 그대로 약물이 모두 제거되는 시점까지 그대로 유지된다는 가정을 세우게 되며, 다음과 같이 Clast(가장 마지막으로 농도를 측정한 시점)에서 λ(Cmax 이후에 선형성이 가장 높은 3점을 선택하여 구한 기울기)를 구한 후 
 
위와 같은 약동학 공식을 대입하여 값을 구해주게 된다.

약물이 우리 몸에 들어온 후 가장 높은 농도의 경우 실제 개개인에서 농도를 측정한 값들 중 가장 높은 농도를 실제 가장 높은 농도라 가정하여 사용하게 되고(이 지표를 Cmax라 지칭한다.), 이 시점을 Tmax라 부르게 된다.
위에서 구한 AUC와 Cmax, λ 를 가지고 나머지 주요 값을 계산하게 된다.
이 중 청소율(제거되는 속도)에 해당하는 clearance(일반적으로 CL이라 지칭한다.) 의 경우 다음의 약동학 기본 공식을 활용하여 구해주게 된다.
 
(다음 수식에서 D는 dose로 투여량을, F는 생체이용률을 의미한다.)
우리 몸의 분포(disposition)을 알기 위해 우리 몸의 volume을 나타내는 volume of distribution at steady state(Vdss)는 
  위 공식을 이용하여 값을 추정하게 되고
추가적으로 우리 몸의 생체이용률을 측정하는 F의 경우(기본적으로 정맥주사시의 생체이용률을 1이라고 가정하게 된다.)
 
다음의 공식을 활용하여 값을 계산한다. (이중 Div는 정맥주사 투여량, Doral은 경구 투여량, AUCoral은 경구 투여에서의 AUC, AUCiv는 정맥투여에서의 AUC를 의미한다.
이처럼 AUC, Cmax, AUMC, λ 를 구하는 부분에 있어서는 non-compartmental analysis의 기본 가정들을 활용하였고 그 밖의 부분들에서는 현재 정형화된 공식들을 활용하여 적용하였다. 
위 내용을 바탕으로 R을 기반으로 한 script를 구성한 후 전세계적으로 널리 쓰이고 있는 CDISC terminology를 각각의 지표들에 적용하여 결과값을 도출하였다. 또한 투여되는 방식을 3가지 분류(Extravascular, IV infusion, IV bolus)로 구분하여, 그에 맞는 각각의 식을 적용하였다. 마지막으로 시간당 농도의 변화율이 농도 증가 곡선보다 감소 곡선에서 완만하다는 점을 고려하여 농도가 감소하는 구간에서는 log값을 선택적으로 줄 수 있도록 설정하였으며, 흡수 속도 상수의 경우 현 NCA method를 통해 구하기에는 한계가 있어 따로 값을 제시하지 않았다. 
흡수속도 상수를 구하기 위해서는 구획분석방법(compartmental analysis)이나 비선형 혼합모형(non-linear mixed effect modeling)을 사용하는 것이 바람직하다.
 
Figure 2. Linear trapezoidal method를 적용한 AUC의 계산 Script

 
Figure 3 약동학 지표들에 대해 각각의 공식을 적용한 Script의 예


# 결과 및 논의 {#result}

현재 테오필린(theophylline)과 인도메타신(indomethacin)에 대해서 NCA 를 구할 수 있도록 시스템을 구축하였다. 약물을 선택한 후 각 약물의 복용량, 감소 구간에서의 log 치환 여부, 복용방법, 정맥주사일 경우 투입 시간(정맥주사 이외의 값들 경우에는 infusion time은 내부 함수에 따라 값이 적용되지 않는다.)을 각각 설정할 경우 값을 도출할 수 있다. 

 
Figure 4 논문 내에서의 설정 값 
Edison 내에서 실제 Theophylline의 용량에 따라 구현된 각각의 graph를 spaghetti plot형태로 Edison의 결과 가시화 tab을 이용하여 확인할 수 있으며, 그래프의 형태를 변형할 수 있게 설정하였다. Y축(농도)의 경우 linear plot과 semi-logarithmic plot을 모두 함께 확인할 수 있도록 하여 다양한 구간에서의 그래프의 추세를 선택적으로 확인할 수 있도록 하였다.
 
Figure 5. 앞서 설정한 Theophylline에 대한 linear spaghetti plot

 
Figure 6. 앞서 설정한 Theophylline에 대한 scatter plot

 
Figure 7. 앞서 설정한 Theophylline에 대한 semi-logarithmic spaghetti plot

언급하였던 공식 이외에도 Pharmacokinetic and Pharmacodynamic Data Analysis 5th edition 에 언급된 공식을 적용하여 다음과 같이 값을 도출하였다.(figure 8) 

또한 결과 값이 모두 도출된 이후 실제 NCA program으로 가장 흔히 사용되고 있는 WinNonlin® (Version 7.0  Pharsight, CA, USA) software 와의 결과 비교에서도 모든 조건을 현재 Edison simulator에서 준 값과 동일하게 설정하여 프로그램을 실행할 경우, 모든 지표에서 같은 값이 계산됨을 확인하였다. (figure 8, figure 9)
 
Figure 8. 앞서 설정한 Theophylline에 대한 NCA 분석 결과

 
Figure 9. Theophylline에 대하여 같은 data와 설정값으로 계산한 WinNonlin® (Version 7.0  Pharsight, CA, USA) software의 결과
현재 가장 간단한 분석 방식인 비구획 분석을 통해서 약동학 분석에 필수적인 지표들을 산출해 내었지만, 마찬가지로 수학적 원리를 반영하여 R script를 구성한다면 보다 고차원적적 약동학 분석 방법인 구획 분석(Compartmental analysis)과 비선형적 약동학(nonlinear mixed effect modeling) 분석 또한 실시할 수 있다. 실제로 Edison 사이언스 엡에 추가한 ‘NONMEM(Nonlinear mixed effect modeling), method’라는 엡을 통해 현재 입력 되어있는 Theoph(theophylline)의 시간 농도 데이터를 가지고 FO(first-order method), FOCE(first-order conditional estimation method), LAPL(Laplace's method)의 방법을 이용하여 현재 사용하는 NONMEM software와 유사한 값들을 재현해 낼 수 있다. 

 
Figure 10. NONMEM(Nonlinear mixed effect modeling), method 엡에 입력되어 있는 theophylline data의 농도 시간 곡선
 
Figure 11. theophylline data에 대한 model

 
Figure 12. nonlinear mixed effect modeling First order method를 통해 도출된 parameter

# 결론 {#conclusion}

약물을 연구하고 개발하는데 있어서 약동학은 굉장히 필수적인 분야이며, 그 동안 이러한 약동학 지표들을 구하기 위해서 그러한 결론이 도출되는 과정을 고려하지 않고 일부 프로그램의 사용에만 의존하는 모습이 주를 이루습니다.
하지만 이번 Edison program과 다양한 수학적, 통계적 지식을 coding에 활용하여 실제 임상적으로도 활용 가능한 결과값을 도출해 낼 수 있음을 확인하였으며 앞으로도 약동학 분야에서 다양하게 활용할 수 있을 것으로 예측됩니다.

# 감사의 글 {#acknowledgement}

본 논문은 2016년도 정부(미래창조과학부)의 재원으로 한국연구재단 첨단 사이언스·교육 허브 개발 사업의 지원을 받아 수행된 연구임(NRF-2016-936606).

# 참고문헌 {#bibliography}

[1] U.S. Department of Health and Human Services Food and Drug Administration Center for Drug Evaluation and Research (CDER) , Guidance for Industry Pharmacokinetics in Pregnancy — Study Design, Data Analysis, and Impact on Dosing and Labeling, (2004)
[2] Malcolm Rowland and Thomas N. Tozer PharmD PhD, Clinical Pharmacokinetics and Pharmacodynamics : Concepts and Applications 4th Ed. 2010 (ISBN:9780781750097)
[3] Hadley Wickham, Advanced R (Chapman & Hall/CRC The R Series) 1st Ed ,25 sep 2014
[4] Gabrielsson J and Weiner D. Pharmacokinetic and Pharmacodynamic Data Analysis - Concepts and Applications. 5th ed. 2016. (ISBN:9198299107).
[5] http://www.edison.re.kr. EDISON 웹사이트. 

