# Details


## In this chapter

We will give you details of each software and perform NCA with a dataset `Theoph`. In the end, we will compare C~max~ and AUC~inf~ calculated by each software or package.

## ncar

## PKNCA

```{r}
library(PKNCA)

my.conc <- PKNCAconc(as.data.frame(Theoph), conc~Time|Subject)
d.dose <- unique(datasets::Theoph[datasets::Theoph$Time == 0,
                                  c("Dose", "Time", "Subject")])
my.dose <- PKNCAdose(d.dose, Dose~Time|Subject)
my.data.automatic <- PKNCAdata(my.conc, my.dose)
my.results.automatic <- pk.nca(my.data.automatic)
my.results.automatic$result %>% filter(grepl(pattern = "cmax|aucinf", PPTESTCD)) %>% 
    arrange(PPTESTCD)
summary(my.results.automatic)
```

## ncappc

```{r eval = FALSE}
library(ncappc)

write.csv(Theoph %>% rename(ID = Subject, TIME = Time, DV = conc), 
          "Theoph.csv", row.names = FALSE)
ncappc(obsFile="Theoph.csv", psnOut = FALSE, noPlot = TRUE, printOut = TRUE, 
       method = "linear-log", evid = FALSE)
Theoph_ncappc <- read.delim("ncaOutput-.tsv", sep = "\t", check.names = FALSE)
Theoph_ncappc[ , c("Cmax (M.L^-3)", "AUCINF_obs (T*M.L^-3)")]
```

```{r echo = FALSE}
Theoph_ncappc <- read.delim("ncaOutput-.tsv", sep = "\t", check.names = FALSE)
Theoph_ncappc[ , c("Cmax (M.L^-3)", "AUCINF_obs (T*M.L^-3)")]
```


## Summary

`ncar` is good.