\cleardoublepage

# (APPENDIX) Appendix {-}

# NonCompart::tblNCA 함수의 인자 {#tblNCA-args}

- concData: concentration data table
- key: olumn names of concData to be shown in the output table
- colTime: column name for time
- colConc: column name for concentration
- dose: administered dose
- adm: one of "Bolus" or "Infusion" or "Extravascular" to indicate drug administration mode
- dur: duration of infusion
- doseUnit: unit of dose
- timeUnit: unit of time
- concUnit: unit of concentration
- down: method to calculate AUC, "Linear" or "Log"
- R2ADJ: Lowest threshold of adjusted R-square value to do manual slope determination
- MW: molecular weight of drug
- iAUC: data.frame for interval AUC


# Phoenix WinNonLin 과 결과 비교 {#wnl-comparison}

## Conclusion 

*There is no discrepancy* between results from NonCompart and WinNonlin. We also performed multiple analyses with the real clinical trial datasets and have found no differences (data not shown: confidential).  Noncompartmental analysis performed by the open-source R package, NonCompart can be **qualified and validated** enough to acquire the identical results of the commercial software, WinNonlin.

*Please report issues regarding validation of the R package to <https://github.com/asancpt/NonCompart-tests/issues>.*

