# R 패키지 {#r-packages}

```{r}
library(tidyverse)
library(NonCompart)
```

## 이 장에서는 {#summary-r-packages}

`NonCompart` [@R-NonCompart],  `ncar` [@R-ncar], `pkr` [@R-pkr] 은 비구획 분석을 R을 통해 쉽고 빠르게 (매우 빠르게) 행할 수 있는 패키지입니다. 
이에 대해 알아보겠습니다.

## 패키지에 대하여

`NonCompart`의 패키지 제목은 `r packageDescription("NonCompart")$Title`, 
`ncar`의 패키지 제목은 `r packageDescription("ncar")$Title`,
`pkr`의 패키지 제목은 `r packageDescription("pkr")$Title` 입니다.

`NonCompart`의 `DESCRIPTION` 파일을 보면 다음과 같이 설명하고 있습니다.

> `r packageDescription('NonCompart')$Description`

`ncar`의 `DESCRIPTION` 파일을 보면 다음과 같이 설명하고 있습니다.

> `r packageDescription('ncar')$Description`

`pkr`의 `DESCRIPTION` 파일을 보면 다음과 같이 설명하고 있습니다.

> `r packageDescription('pkr')$Description`

## 설치 

우선 R을 설치합니다. 
R은 아래 링크에서 다운로드 받을 수 있습니다.
<https://r-project.org/>

R을 실행한 후, 아래와 같이 패키지를 설치합니다. 

```r
install.packages('NonCompart')
install.packages('ncar')
install.packages('pkr')
```

이제 아래와 같이 입력하여 패키지를 불러올 수 있습니다.

```r
library(NonCompart)
library(ncar)
library(pkr)
```

## 기타 설치

자료 분석을 위해 몇가지 도구가 필요한데 `tidyverse`[@R-tidyverse]를 설치하면 다수의 편리한 패키지[@R-tidyr; @R-dplyr; @R-tibble; @R-ggplot2]의 설치와 불러오기 과정을 쉽게 끝낼 수 있습니다. 
이 책에서는 이를 주로 사용하겠습니다.  
다음과 같이 설치하고 불러올 수 있습니다.

```r
install.packages('devtools')
devtools::install_github('tidyverse/tidyverse')
library(tidyverse)
```

