# R과 그 패키지에 대하여 {#R-and-packages}

## 이 장에서는 {#summary-r-packages}

R [@R-base]은 통계 소프트웨어 입니다. 
굉장히 유용한 소프트웨어이지만 이에 대해 여기서 자세히 설명하긴 힘듭니다. 
R에 대한 많은 책들을 bookdown.org^[https://bookdown.org]에서 무료로 읽을 수 있습니다. 

또한 이 책에서 주로 다루게 될 `NonCompart` [@R-NonCompart],  `ncar` [@R-ncar], `pkr` [@R-pkr] 은 비구획 분석을 R을 통해 쉽고 빠르게 (매우 빠르게) 행할 수 있는 R 패키지입니다.

`NonCompart`의 패키지 제목은 `r packageDescription("NonCompart")$Title`, 
`ncar`의 패키지 제목은 `r packageDescription("ncar")$Title`,
`pkr`의 패키지 제목은 `r packageDescription("pkr")$Title` 입니다.

## 설치 {#install}

우선 R을 설치합니다. 
R은 아래 링크에서 다운로드 받을 수 있습니다.
<https://r-project.org/>

R을 실행한 후, 아래와 같이 패키지를 설치합니다. 

```r
install.packages('NonCompart')
install.packages('ncar')
install.packages('pkr')
```

이제 아래와 같이 입력하여 패키지를 불러올 수 있습니다.

```r
library(NonCompart)
library(ncar)
library(pkr)
```

## 기타 설치

자료 분석을 위해 몇가지 도구가 필요한데 `tidyverse`[@R-tidyverse]를 설치하면 다수의 편리한 패키지[@R-tidyr; @R-dplyr; @R-tibble; @R-ggplot2; @R-purrr; @R-readr]의 설치와 불러오기 과정을 쉽게 끝낼 수 있습니다. 
이 책에서는 이를 주로 사용하겠습니다.  
다음과 같이 설치하고 불러올 수 있습니다.
다만 비구획분석을 위한 함수의 입력을 위해 `tibble` 형식은 `as.data.frame()`을 통하여 데이타프레임으로 자료 형식을 변환하는 것이 좋습니다.

```r
install.packages('devtools')
devtools::install_github('tidyverse/tidyverse')
library(tidyverse)
```

## 기본적인 R 사용법 {#basic}

R의 사용법을 익히는 것은 여러모로 유용합니다. 특히 자료의 재현가능한 편집이라는 측면이 가장 중요합니다. 오류를 줄일 수 있고, 한번 설정한 것을 반복해서 적용하는 것이 쉽기 때문입니다.
