<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Noncompartmental Analysis by R Packages</title>
  <meta name="description" content="In this book, we will compare, review and discuss R Packages for noncompartmental analysis.">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="Noncompartmental Analysis by R Packages" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://asancpt.github.io/NonCompartBook" />
  <meta property="og:image" content="http://asancpt.github.io/NonCompartBookcover.jpg" />
  <meta property="og:description" content="In this book, we will compare, review and discuss R Packages for noncompartmental analysis." />
  <meta name="github-repo" content="asancpt/NonCompartBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Noncompartmental Analysis by R Packages" />
  
  <meta name="twitter:description" content="In this book, we will compare, review and discuss R Packages for noncompartmental analysis." />
  <meta name="twitter:image" content="http://asancpt.github.io/NonCompartBookcover.jpg" />

<meta name="author" content="Kyun-Seop Bae">
<meta name="author" content="Sungpil Han">
<meta name="author" content="Seok Kyu Yoon">
<meta name="author" content="Yong-Soon Cho">


<meta name="date" content="2017-07-11">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="nca-r-.html">
<link rel="next" href="DetailsNCA.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="css\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Noncompartmental Analysis by R Packages</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>책 머리에</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ec9a94ec95bd"><i class="fa fa-check"></i>요약</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> 서론</a></li>
<li class="chapter" data-level="2" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>2</b> 이론 및 계산 방법</a></li>
<li class="chapter" data-level="3" data-path="nca-r-.html"><a href="nca-r-.html"><i class="fa fa-check"></i><b>3</b> NCA를 위한 R 패키지</a><ul>
<li class="chapter" data-level="3.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>3.1</b> 이 장에서는</a></li>
<li class="chapter" data-level="3.2" data-path="nca-r-.html"><a href="nca-r-.html#noncompart-ncar"><i class="fa fa-check"></i><b>3.2</b> NonCompart, ncar란?</a></li>
<li class="chapter" data-level="3.3" data-path="nca-r-.html"><a href="nca-r-.html#section-3.3"><i class="fa fa-check"></i><b>3.3</b> 설치</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="noncompart-.html"><a href="noncompart-.html"><i class="fa fa-check"></i><b>4</b> NonCompart 사용법</a><ul>
<li class="chapter" data-level="4.1" data-path="noncompart-.html"><a href="noncompart-.html#TheophData"><i class="fa fa-check"></i><b>4.1</b> 데이타에 대하여</a></li>
<li class="chapter" data-level="4.2" data-path="noncompart-.html"><a href="noncompart-.html#calculation-setting"><i class="fa fa-check"></i><b>4.2</b> Calculation Setting</a></li>
<li class="chapter" data-level="4.3" data-path="noncompart-.html"><a href="noncompart-.html#fitting-auc-aumc-result"><i class="fa fa-check"></i><b>4.3</b> Fitting, AUC, AUMC Result</a></li>
<li class="chapter" data-level="4.4" data-path="noncompart-.html"><a href="noncompart-.html#time-conc.-pred.-residual-auc-aumc-weight"><i class="fa fa-check"></i><b>4.4</b> Time Conc. Pred. Residual AUC AUMC Weight</a></li>
<li class="chapter" data-level="4.5" data-path="noncompart-.html"><a href="noncompart-.html#calculated-values"><i class="fa fa-check"></i><b>4.5</b> Calculated Values</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="DetailsNCA.html"><a href="DetailsNCA.html"><i class="fa fa-check"></i><b>5</b> NCA 소프트웨어</a><ul>
<li class="chapter" data-level="5.1" data-path="DetailsNCA.html"><a href="DetailsNCA.html#detailschapter"><i class="fa fa-check"></i><b>5.1</b> 이 장에서는</a></li>
<li class="chapter" data-level="5.2" data-path="DetailsNCA.html"><a href="DetailsNCA.html#certara-phoenix-winnonlin"><i class="fa fa-check"></i><b>5.2</b> Certara Phoenix WinNonLin</a><ul>
<li class="chapter" data-level="5.2.1" data-path="DetailsNCA.html"><a href="DetailsNCA.html#pros"><i class="fa fa-check"></i><b>5.2.1</b> Pros</a></li>
<li class="chapter" data-level="5.2.2" data-path="DetailsNCA.html"><a href="DetailsNCA.html#cons"><i class="fa fa-check"></i><b>5.2.2</b> Cons</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="DetailsNCA.html"><a href="DetailsNCA.html#r-package-pkr"><i class="fa fa-check"></i><b>5.3</b> R package: pkr</a><ul>
<li class="chapter" data-level="5.3.1" data-path="DetailsNCA.html"><a href="DetailsNCA.html#pros-1"><i class="fa fa-check"></i><b>5.3.1</b> Pros</a></li>
<li class="chapter" data-level="5.3.2" data-path="DetailsNCA.html"><a href="DetailsNCA.html#cons-1"><i class="fa fa-check"></i><b>5.3.2</b> Cons</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="DetailsNCA.html"><a href="DetailsNCA.html#r-package-pknca"><i class="fa fa-check"></i><b>5.4</b> R package: PKNCA</a><ul>
<li class="chapter" data-level="5.4.1" data-path="DetailsNCA.html"><a href="DetailsNCA.html#pros-2"><i class="fa fa-check"></i><b>5.4.1</b> Pros</a></li>
<li class="chapter" data-level="5.4.2" data-path="DetailsNCA.html"><a href="DetailsNCA.html#cons-2"><i class="fa fa-check"></i><b>5.4.2</b> Cons</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="DetailsNCA.html"><a href="DetailsNCA.html#r-package-ncappc"><i class="fa fa-check"></i><b>5.5</b> R package: ncappc</a></li>
<li class="chapter" data-level="5.6" data-path="DetailsNCA.html"><a href="DetailsNCA.html#r-package-pk"><i class="fa fa-check"></i><b>5.6</b> R package: PK</a></li>
<li class="chapter" data-level="5.7" data-path="DetailsNCA.html"><a href="DetailsNCA.html#kinetica"><i class="fa fa-check"></i><b>5.7</b> Kinetica</a></li>
<li class="chapter" data-level="5.8" data-path="DetailsNCA.html"><a href="DetailsNCA.html#scientist"><i class="fa fa-check"></i><b>5.8</b> Scientist</a></li>
<li class="chapter" data-level="5.9" data-path="DetailsNCA.html"><a href="DetailsNCA.html#pksolver"><i class="fa fa-check"></i><b>5.9</b> PKSolver</a></li>
<li class="chapter" data-level="5.10" data-path="DetailsNCA.html"><a href="DetailsNCA.html#summary"><i class="fa fa-check"></i><b>5.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="result.html"><a href="result.html"><i class="fa fa-check"></i><b>6</b> 결과 및 논의</a></li>
<li class="chapter" data-level="7" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>7</b> 결론</a></li>
<li class="chapter" data-level="8" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i><b>8</b> 감사의 글</a><ul>
<li class="chapter" data-level="8.0.1" data-path="acknowledgement.html"><a href="acknowledgement.html#isop-pharmacometrics-study-group-presentation"><i class="fa fa-check"></i><b>8.0.1</b> ISoP Pharmacometrics Study Group Presentation</a></li>
<li class="chapter" data-level="8.0.2" data-path="acknowledgement.html"><a href="acknowledgement.html#-nca----."><i class="fa fa-check"></i><b>8.0.2</b> 오픈소스 NCA - 지금이 적기이다.</a></li>
<li class="chapter" data-level="8.0.3" data-path="acknowledgement.html"><a href="acknowledgement.html#section-8.0.3"><i class="fa fa-check"></i><b>8.0.3</b> 한계</a></li>
<li class="chapter" data-level="8.0.4" data-path="acknowledgement.html"><a href="acknowledgement.html#pknca--0.7"><i class="fa fa-check"></i><b>8.0.4</b> PKNCA 현재는 0.7</a></li>
<li class="chapter" data-level="8.0.5" data-path="acknowledgement.html"><a href="acknowledgement.html#pknca--1.0-."><i class="fa fa-check"></i><b>8.0.5</b> PKNCA 곧 1.0이 나올것이다.</a></li>
<li class="chapter" data-level="8.0.6" data-path="acknowledgement.html"><a href="acknowledgement.html#section-8.0.6"><i class="fa fa-check"></i><b>8.0.6</b> 참고사항</a></li>
<li class="chapter" data-level="8.0.7" data-path="acknowledgement.html"><a href="acknowledgement.html#rstudio--hands-on-"><i class="fa fa-check"></i><b>8.0.7</b> RStudio를 사용한 Hands-on 실습</a></li>
<li class="chapter" data-level="8.0.8" data-path="acknowledgement.html"><a href="acknowledgement.html#closing"><i class="fa fa-check"></i><b>8.0.8</b> Closing</a></li>
<li class="chapter" data-level="8.0.9" data-path="acknowledgement.html"><a href="acknowledgement.html#section-8.0.9"><i class="fa fa-check"></i><b>8.0.9</b> 결론</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="http://github.com/asancpt/ncar">ncar Github Repo</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Noncompartmental Analysis by R Packages</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="noncompart-" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> NonCompart 사용법</h1>
<p>김민걸 선생님 자료를 옮겨와서 변형합니다. <a href="http://blog.naver.com/kimmingul" class="uri">http://blog.naver.com/kimmingul</a></p>
<div id="TheophData" class="section level2">
<h2><span class="header-section-number">4.1</span> 데이타에 대하여</h2>
<p>아산병원 배균섭 교수님께서 만드신 NonCompart 패키지 사용법에 대해서 간략히 적어봅니다. 뭐 별로 복잡한 것은 아니지만, R 초심자들을 위해 설치단계부터… (참고로 첫칸의 &gt; 기호는 R에서 프롬프트 이므로 이는 타이핑하지 않는다.)</p>
<p>R에는 theophylline과 Indomethacin의 약동학 데이터가 내장되어 있습니다.</p>
<ul>
<li><code>Theoph</code>: theophylline의 약동학 데이터, 12명, 320mg PO 단회투여, 0~24시간 채혈, NONMEM 의 run 폴더의 THEOPP 데이터와 동일합니다.</li>
<li><code>Indometh</code>: Indomethacin의 약동학 데이터, 6명, 25mg IV bolus 단회투여, 0~8시간 채혈(0, 0.25, 0.5, 0.75, 1, 1.25, 2, 3, 4, 5, 6, 8 h) (데이터명의 첫글짜가 대문자임에 주의하길)</li>
</ul>
<p>데이터를 살펴보겠습니다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(Theoph)</code></pre></div>
<pre><code>##   Subject   Wt Dose Time  conc
## 1       1 79.6 4.02 0.00  0.74
## 2       1 79.6 4.02 0.25  2.84
## 3       1 79.6 4.02 0.57  6.57
## 4       1 79.6 4.02 1.12 10.50
## 5       1 79.6 4.02 2.02  9.66
## 6       1 79.6 4.02 3.82  8.58</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(Theoph)</code></pre></div>
<pre><code>##     Subject   Wt Dose  Time conc
## 127      12 60.5  5.3  3.52 9.75
## 128      12 60.5  5.3  5.07 8.57
## 129      12 60.5  5.3  7.07 6.59
## 130      12 60.5  5.3  9.03 6.11
## 131      12 60.5  5.3 12.05 4.57
## 132      12 60.5  5.3 24.15 1.17</code></pre>
<p>데이터가 Subject, weight, Dose, Time, Concentration 으로 구성되었음을 알 수 있습니다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Backbone &lt;-<span class="st"> </span><span class="kw">ggplot</span>(Theoph <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">                       </span><span class="kw">mutate</span>(<span class="dt">Subject =</span> <span class="kw">as.numeric</span>(Subject)), 
                   <span class="kw">aes</span>(Time, conc, <span class="dt">group =</span> Subject, <span class="dt">colour =</span> Wt)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() 

Individual &lt;-<span class="st"> </span>Backbone <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_log10</span>()
groupLinear &lt;-<span class="st"> </span>Backbone
groupLog &lt;-<span class="st"> </span>groupLinear <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_log10</span>()

<span class="kw">ggdraw</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">draw_plot</span>(Individual, <span class="dv">0</span>, .<span class="dv">5</span>, <span class="dv">1</span>, .<span class="dv">5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">draw_plot</span>(groupLinear, <span class="dv">0</span>, <span class="dv">0</span>, .<span class="dv">5</span>, .<span class="dv">5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">draw_plot</span>(groupLog, .<span class="dv">5</span>, <span class="dv">0</span>, .<span class="dv">5</span>, .<span class="dv">5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">draw_plot_label</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>), <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.5</span>), <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="dt">size =</span> <span class="dv">15</span>)</code></pre></div>
<pre><code>## Warning: Transformation introduced infinite values in continuous y-axis

## Warning: Transformation introduced infinite values in continuous y-axis

## Warning: Transformation introduced infinite values in continuous y-axis

## Warning: Transformation introduced infinite values in continuous y-axis</code></pre>
<div class="figure"><span id="fig:TheophFig"></span>
<img src="ncarBook_files/figure-html/TheophFig-1.png" alt="Theoph 데이타를 시각화. A) Individual concentration-time curves, B) linear concentration-time curves, C) semi-logarithmic concentration-time curves" width="768" />
<p class="caption">
Figure 4.1: Theoph 데이타를 시각화. A) Individual concentration-time curves, B) linear concentration-time curves, C) semi-logarithmic concentration-time curves
</p>
</div>
<p>이 패키지로 NCA 비구획방법으로 약동학 파라미터를 산출하기 위해서는 아래와 같이 하면 된다.<br />
우선 Theophilline 의 약동학 파라미터를 구해보면,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NonCompart<span class="op">::</span><span class="kw">tabNCA</span>(Theoph, <span class="st">&quot;Subject&quot;</span>, <span class="st">&quot;Time&quot;</span>, <span class="st">&quot;conc&quot;</span>, <span class="dt">dose=</span><span class="dv">320</span>)</code></pre></div>
<pre><code>##       ID       b0  CMAX      CMAXD TMAX TLAG CLST     CLSTP  TLST
##  [1,] 11 2.368785 10.50 0.03281250 1.12    0 3.28 3.2801465 24.37
##  [2,]  6 2.411237  8.33 0.02603125 1.92    0 0.90 0.8886398 24.30
##  [3,]  5 2.529712  8.20 0.02562500 1.02    0 1.05 1.0550967 24.17
##  [4,]  7 2.592755  8.60 0.02687500 1.07    0 1.15 1.1564216 24.65
##  [5,] 12 2.551092 11.40 0.03562500 1.00    0 1.57 1.5556951 24.35
##  [6,]  1 2.033404  6.44 0.02012500 1.15    0 0.92 0.9412712 23.85
##  [7,]  2 2.288550  7.09 0.02215625 3.48    0 1.15 1.1607192 24.22
##  [8,]  3 2.170403  7.56 0.02362500 2.02    0 1.25 1.2285268 24.12
##  [9,]  8 2.124648  9.03 0.02821875 0.63    0 1.12 1.1164831 24.43
## [10,] 10 2.657705 10.21 0.03190625 3.55    0 2.42 2.4136923 23.70
## [11,]  4 2.147594  8.00 0.02500000 0.98    0 0.86 0.8598066 24.08
## [12,]  9 2.824493  9.75 0.03046875 3.52    0 1.17 1.1755390 24.15
##          LAMZHL       LAMZ LAMZLL LAMZUL LAMZNPT     CORRXY        R2
##  [1,] 14.304378 0.04845700   9.05  24.37       3 -0.9999999 0.9999997
##  [2,]  6.659342 0.10408644   7.03  24.30       4 -0.9985967 0.9971954
##  [3,]  6.766087 0.10244431   9.00  24.17       3 -0.9996624 0.9993250
##  [4,]  6.981247 0.09928702   9.02  24.65       3 -0.9994619 0.9989241
##  [5,]  8.002264 0.08661888   7.02  24.35       4 -0.9993234 0.9986472
##  [6,]  7.894998 0.08779574   2.03  23.85       7 -0.9991203 0.9982413
##  [7,]  7.846668 0.08833650   6.98  24.22       4 -0.9993349 0.9986702
##  [8,]  8.510038 0.08145054   3.53  24.12       6 -0.9954961 0.9910124
##  [9,]  8.405999 0.08245863   8.80  24.43       3 -0.9997218 0.9994437
## [10,]  9.246916 0.07495982   9.38  23.70       3 -0.9997543 0.9995087
## [11,]  7.261237 0.09545856   9.03  24.08       3 -0.9999991 0.9999983
## [12,]  6.286508 0.11025949   9.03  24.15       3 -0.9996984 0.9993968
##           R2ADJ    AUCLST    AUCALL    AUCIFO   AUCIFOD    AUCIFP
##  [1,] 0.9999995 148.92305 148.92305 216.61193 0.6769123 216.61496
##  [2,] 0.9957931  91.52680  91.52680 100.17346 0.3130421 100.06432
##  [3,] 0.9986499  99.28650  99.28650 109.53597 0.3422999 109.58572
##  [4,] 0.9978483 106.79630 106.79630 118.37888 0.3699340 118.44356
##  [5,] 0.9979708 121.29440 121.29440 139.41978 0.4356868 139.25463
##  [6,] 0.9978896  73.77555  73.77555  84.25442 0.2632951  84.49670
##  [7,] 0.9980053  90.75340  90.75340 103.77180 0.3242869 103.89315
##  [8,] 0.9887655  88.55995  88.55995 103.90669 0.3247084 103.64305
##  [9,] 0.9988873  86.32615  86.32615  99.90872 0.3122147  99.86607
## [10,] 0.9990174 138.36810 138.36810 170.65206 0.5332877 170.56791
## [11,] 0.9999965  80.09360  80.09360  89.10274 0.2784461  89.10072
## [12,] 0.9987936 119.97750 119.97750 130.58883 0.4080901 130.63907
##         AUCIFPD    AUCPEO    AUCPEP   AUMCLST   AUMCIFO   AUMCIFP  AUMCPEO
##  [1,] 0.6769217 31.248917 31.249876 1459.0711 4505.5348 4505.6709 67.61603
##  [2,] 0.3127010  8.631687  8.532030  706.5866  999.7723  996.0716 29.32525
##  [3,] 0.3424554  9.357173  9.398325  803.1859 1150.9648 1152.6529 30.21629
##  [4,] 0.3701361  9.784331  9.833594  901.0842 1303.2524 1305.4981 30.85881
##  [5,] 0.4351707 13.000579 12.897403 1017.1143 1667.7216 1661.7937 39.01174
##  [6,] 0.2640522 12.437174 12.688246  609.1524  978.4285  986.9665 37.74176
##  [7,] 0.3246661 12.545221 12.647366  782.4199 1245.0984 1249.4111 37.16000
##  [8,] 0.3238845 14.769730 14.552931  739.5346 1298.1158 1288.5201 43.03015
##  [9,] 0.3120815 13.594978 13.558076  705.2296 1201.7715 1200.2124 41.31750
## [10,] 0.5330247 18.918002 18.878001 1278.1800 2473.9934 2470.8765 48.33535
## [11,] 0.2784397 10.110962 10.108918  617.2422  928.5600  928.4900 33.52694
## [12,] 0.4082471  8.125757  8.161087  977.8807 1330.3840 1332.0528 26.49636
##        AUMCPEP MRTEVLST  MRTEVIFO  MRTEVIFP     VZFO     VZFP     CLFO
##  [1,] 67.61701 9.797483 20.800031 20.800368 30486.75 30486.32 1477.296
##  [2,] 29.06267 7.719996  9.980411  9.954313 30690.44 30723.92 3194.459
##  [3,] 30.31850 8.089578 10.507642 10.518276 28517.10 28504.15 2921.415
##  [4,] 30.97775 8.437410 11.009163 11.022112 27225.96 27211.10 2703.185
##  [5,] 38.79419 8.385501 11.961873 11.933490 26497.99 26529.42 2295.227
##  [6,] 38.28034 8.256833 11.612785 11.680533 43259.73 43135.69 3798.020
##  [7,] 37.37691 8.621383 11.998427 12.025924 34908.44 34867.67 3083.689
##  [8,] 42.60589 8.350666 12.493092 12.432287 37810.51 37906.69 3079.686
##  [9,] 41.24126 8.169363 12.028695 12.018220 38842.79 38859.38 3202.924
## [10,] 48.27018 9.237534 14.497296 14.486174 25015.54 25027.88 1875.160
## [11,] 33.52193 7.706511 10.421227 10.420679 37622.19 37623.04 3591.360
## [12,] 26.58844 8.150534 10.187579 10.196436 22224.29 22215.75 2450.439
##           CLFP
##  [1,] 1477.276
##  [2,] 3197.943
##  [3,] 2920.088
##  [4,] 2701.709
##  [5,] 2297.949
##  [6,] 3787.130
##  [7,] 3080.088
##  [8,] 3087.520
##  [9,] 3204.292
## [10,] 1876.086
## [11,] 3591.441
## [12,] 2449.497
## attr(,&quot;units&quot;)
##  [1] &quot;&quot;          &quot;&quot;          &quot;ug/L&quot;      &quot;ug/L/mg&quot;   &quot;h&quot;        
##  [6] &quot;h&quot;         &quot;ug/L&quot;      &quot;ug/L&quot;      &quot;h&quot;         &quot;h&quot;        
## [11] &quot;/h&quot;        &quot;h&quot;         &quot;h&quot;         &quot;&quot;          &quot;&quot;         
## [16] &quot;&quot;          &quot;&quot;          &quot;h*ug/L&quot;    &quot;h*ug/L&quot;    &quot;h*ug/L&quot;   
## [21] &quot;h*ug/L/mg&quot; &quot;h*ug/L&quot;    &quot;h*ug/L/mg&quot; &quot;%&quot;         &quot;%&quot;        
## [26] &quot;h2*ug/L&quot;   &quot;h2*ug/L&quot;   &quot;h2*ug/L&quot;   &quot;%&quot;         &quot;%&quot;        
## [31] &quot;h&quot;         &quot;h&quot;         &quot;h&quot;         &quot;L&quot;         &quot;L&quot;        
## [36] &quot;L/h&quot;       &quot;L/h&quot;</code></pre>
<p>다음으로 Indomethacin 의 약동학 파라미터를 구해보자. 이는 IV bolus 이므로 AdmMode 옵션이 추가된다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NonCompart<span class="op">::</span><span class="kw">tabNCA</span>(Indometh, <span class="st">&quot;Subject&quot;</span>, <span class="st">&quot;time&quot;</span>, <span class="st">&quot;conc&quot;</span>, <span class="dt">dose=</span><span class="dv">25</span>, <span class="dt">adm=</span><span class="st">&quot;Bolus&quot;</span>, <span class="dt">dur=</span><span class="fl">0.5</span>, <span class="dt">concUnit=</span><span class="st">&quot;mg/L&quot;</span>)</code></pre></div>
<pre><code>##      ID          b0 CMAX  CMAXD TMAX CLST      CLSTP TLST   LAMZHL
## [1,]  1 -1.72421060 1.50 0.0600 0.25 0.05 0.05024851    8 4.378127
## [2,]  3 -0.17528686 2.03 0.0812 0.25 0.08 0.07475591    8 2.293063
## [3,]  6  0.15557954 2.72 0.1088 0.25 0.08 0.03997258    8 1.642947
## [4,]  2  0.20029695 1.85 0.0740 0.25 0.07 0.03196011    8 1.521910
## [5,]  4 -0.98235713 2.05 0.0820 0.25 0.06 0.04957149    8 2.742446
## [6,]  5 -0.04991898 2.31 0.0924 0.25 0.09 0.05624247    8 1.960699
##           LAMZ LAMZLL LAMZUL LAMZNPT     CORRXY        R2     R2ADJ
## [1,] 0.1583205   5.00      8       3 -0.9985323 0.9970667 0.9941335
## [2,] 0.3022800   0.75      8       9 -0.9734830 0.9476691 0.9401933
## [3,] 0.4218926   0.50      8      10 -0.9358558 0.8758261 0.8603043
## [4,] 0.4554455   0.25      8      11 -0.9342510 0.8728249 0.8586943
## [5,] 0.2527478   1.00      8       8 -0.9355449 0.8752442 0.8544516
## [6,] 0.3535205   0.75      8       9 -0.9507649 0.9039538 0.8902329
##            C0   AUCLST   AUCALL   AUCIFO    AUCIFOD   AUCIFP    AUCIFPD
## [1,] 2.393617 2.040452 2.040452 2.356267 0.09425069 2.357837 0.09431348
## [2,] 2.528160 3.248520 3.248520 3.513175 0.14052701 3.495827 0.13983307
## [3,] 4.965369 3.554421 3.554421 3.744043 0.14976171 3.649167 0.14596668
## [4,] 2.462230 2.785279 2.785279 2.938974 0.11755898 2.855452 0.11421808
## [5,] 4.040865 2.458858 2.458858 2.696249 0.10784996 2.654988 0.10619954
## [6,] 3.705625 3.335703 3.335703 3.590285 0.14361141 3.494796 0.13979183
##         AUCPEO    AUCPEP  AUCPBEO  AUCPBEP  AUMCLST  AUMCIFO  AUMCIFP
## [1,] 13.403196 13.460844 20.65564 20.64189 3.271250 7.792554 7.815026
## [2,]  7.533221  7.074344 16.21809 16.29857 6.398750 9.391522 9.195343
## [3,]  5.064624  2.596369 25.65866 26.32577 5.006250 6.972678 5.988790
## [4,]  5.229568  2.457520 18.34071 18.87718 4.381875 5.948903 5.097338
## [5,]  8.804484  7.387236 28.23768 28.67652 3.707500 6.545866 6.052534
## [6,]  7.090860  4.552269 20.94411 21.51637 5.532500 8.289291 7.255264
##       AUMCPEO  AUMCPEP MRTIVLST MRTIVIFO MRTIVIFP      VZO      VZP
## [1,] 58.02083 58.14153 1.353199 3.057161 3.064490 67.01598 66.97136
## [2,] 31.86674 30.41314 1.719743 2.423229 2.380377 23.54132 23.65814
## [3,] 28.20191 16.40632 1.158457 1.612339 1.391139 15.82695 16.23844
## [4,] 26.34146 14.03601 1.323227 1.774142 1.535125 18.67703 19.22334
## [5,] 43.36120 38.74467 1.257814 2.177768 2.029684 36.68535 37.25547
## [6,] 33.25726 23.74502 1.408571 2.058811 1.826019 19.69683 20.23502
##            CLO       CLP     VSSO      VSSP
## [1,] 10.610002 10.602939 32.43648 32.492596
## [2,]  7.116070  7.151384 17.24387 17.022991
## [3,]  6.677274  6.850879 10.76603  9.530524
## [4,]  8.506369  8.755181 15.09151 13.440293
## [5,]  9.272141  9.416237 20.19257 19.111984
## [6,]  6.963235  7.153494 14.33599 13.062419
## attr(,&quot;units&quot;)
##  [1] &quot;&quot;          &quot;&quot;          &quot;mg/L&quot;      &quot;mg/L/mg&quot;   &quot;h&quot;        
##  [6] &quot;mg/L&quot;      &quot;mg/L&quot;      &quot;h&quot;         &quot;h&quot;         &quot;/h&quot;       
## [11] &quot;h&quot;         &quot;h&quot;         &quot;&quot;          &quot;&quot;          &quot;&quot;         
## [16] &quot;&quot;          &quot;mg/L&quot;      &quot;h*mg/L&quot;    &quot;h*mg/L&quot;    &quot;h*mg/L&quot;   
## [21] &quot;h*mg/L/mg&quot; &quot;h*mg/L&quot;    &quot;h*mg/L/mg&quot; &quot;%&quot;         &quot;%&quot;        
## [26] &quot;%&quot;         &quot;%&quot;         &quot;h2*mg/L&quot;   &quot;h2*mg/L&quot;   &quot;h2*mg/L&quot;  
## [31] &quot;%&quot;         &quot;%&quot;         &quot;h&quot;         &quot;h&quot;         &quot;h&quot;        
## [36] &quot;L&quot;         &quot;L&quot;         &quot;L/h&quot;       &quot;L/h&quot;       &quot;L&quot;        
## [41] &quot;L&quot;</code></pre>
<p>NCA의 사용법은 다음과 같다. NCA(Data, colSubj, colTime, colConc, colTrt, Method = “Linear”, Dose = 0, AdmMode = “Extravascular”, TimeInfusion = 0, Report = “Table”, iAUC) Data는 데이터셋을 설정하며. colSubj는 subject ID의 컬럼명, colTime은 time의 컬럼명, colConc는 concentration의 컬럼명, colTrT는 treatment code의 컬럼명(교차시험에서 사용)이다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tabNCA</span>(concData, <span class="dt">colSubj =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">colTime =</span> <span class="st">&quot;Time&quot;</span>, <span class="dt">colConc =</span> <span class="st">&quot;conc&quot;</span>, <span class="dt">dose =</span> <span class="dv">0</span>, 
       <span class="dt">adm =</span> <span class="st">&quot;Extravascular&quot;</span>, <span class="dt">dur =</span> <span class="dv">0</span>, <span class="dt">doseUnit =</span> <span class="st">&quot;mg&quot;</span>, <span class="dt">timeUnit =</span> <span class="st">&quot;h&quot;</span>, 
       <span class="dt">concUnit =</span> <span class="st">&quot;ug/L&quot;</span>, <span class="dt">down =</span> <span class="st">&quot;Linear&quot;</span>, <span class="dt">MW =</span> <span class="dv">0</span>, <span class="dt">returnNA =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>NCA의 옵션들에 대해서 간단히 살펴보자면 다음과 같다.</p>
<ol style="list-style-type: decimal">
<li>Method
<ul>
<li>AUC와 AUMC를 구하는 trapezoidal method 설정, 기본값은 Method=“Linear”</li>
<li>Linear와 Log 중 선택 가능하다.</li>
<li>Linear는 Linear trapezoidal method이며, Log는 Linear-up and log-down method 이다.</li>
</ul></li>
<li>Dose
<ul>
<li>투여량에 대한 설정이다. 단위에 주의해야 한다. 벡터값을 줌으로서 각 대상자별 용량을 다르게 할 수 있다.</li>
</ul></li>
<li>AdmMode
<ul>
<li>투여경로에 대한 설정, 기본값은 AdmMode= “Extravascular”</li>
<li>Bolus, Infusion, Extravascular 중에서 선택 가능하다.</li>
</ul></li>
<li>TimeInfusion
<ul>
<li>주입하는 기간(infusion duration)을 설정한다. 기본값은 0이다.</li>
</ul></li>
<li>Report
<ul>
<li>출력물의 형태. 기본값은 Report=“Table” 이다.</li>
<li>Table, Text 증에서 선택 가능하다.</li>
</ul></li>
<li>iAUC
<ul>
<li>일부구간에 대한 AUC를 구하기 위한 구간설정 옵션이다.</li>
<li>“Name”, “Start”, “End” 3개의 컬럼으로 구성된 데이터 프레임으로 설정해야 한다.</li>
</ul></li>
</ol>
<p>일부 구간의 AUC를 구하는 방법은 조금 더 복잡하므로 자세히 알아보자. 예를 들어 0~12시간까지의 AUC, 0~24시간까지의 AUC를 구하고자 한다면 다음과 같이 하면 된다. 먼저 구하고자 하는 구간에 대한 정보를 갖는 변수를 아래와같이 생성한다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">iAUC =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Name=</span><span class="kw">c</span>(<span class="st">&quot;AUC[0-12h]&quot;</span>,<span class="st">&quot;AUC[0-24h]&quot;</span>), <span class="dt">Start=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="dt">End=</span><span class="kw">c</span>(<span class="dv">12</span>,<span class="dv">24</span>)) ; iAUC</code></pre></div>
<pre><code>##         Name Start End
## 1 AUC[0-12h]     0  12
## 2 AUC[0-24h]     0  24</code></pre>
<pre><code>    Name Start End</code></pre>
<p>1 AUC[0-12h] 0 12 2 AUC[0-24h] 0 24</p>
<p>이제 iAUC 옵션을 이용해서 이를 구한다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># tabNCA(Theoph, &quot;Subject&quot;, &quot;Time&quot;, &quot;conc&quot;, dose=320, iAUC=iAUC)</span></code></pre></div>
<p>Subject CMAX CMAXD TMAX TLAG CLST CLSTP TLST LAMZHL LAMZ LAMZLL LAMZUL LAMZNPT CORRXY R2 R2ADJ 1 1 10.50 0.03281250 1.12 0 3.28 3.2801465 24.37 14.304378 0.04845700 9.05 24.37 3 -0.9999999 0.9999997 0.9999995 2 2 8.33 0.02603125 1.92 0 0.90 0.8886398 24.30 6.659342 0.10408644 7.03 24.30 4 -0.9985967 0.9971954 0.9957931 3 3 8.20 0.02562500 1.02 0 1.05 1.0550967 24.17 6.766087 0.10244431 9.00 24.17 3 -0.9996624 0.9993250 0.9986499 4 4 8.60 0.02687500 1.07 0 1.15 1.1564216 24.65 6.981247 0.09928702 9.02 24.65 3 -0.9994619 0.9989241 0.9978483 5 5 11.40 0.03562500 1.00 0 1.57 1.5556951 24.35 8.002264 0.08661888 7.02 24.35 4 -0.9993234 0.9986472 0.9979708 6 6 6.44 0.02012500 1.15 0 0.92 0.9412712 23.85 7.894998 0.08779574 2.03 23.85 7 -0.9991203 0.9982413 0.9978896 7 7 7.09 0.02215625 3.48 0 1.15 1.1607192 24.22 7.846668 0.08833650 6.98 24.22 4 -0.9993349 0.9986702 0.9980053 8 8 7.56 0.02362500 2.02 0 1.25 1.2285268 24.12 8.510038 0.08145054 3.53 24.12 6 -0.9954961 0.9910124 0.9887655 9 9 9.03 0.02821875 0.63 0 1.12 1.1164831 24.43 8.405999 0.08245863 8.80 24.43 3 -0.9997218 0.9994437 0.9988873 10 10 10.21 0.03190625 3.55 0 2.42 2.4136923 23.70 9.246916 0.07495982 9.38 23.70 3 -0.9997543 0.9995087 0.9990174 11 11 8.00 0.02500000 0.98 0 0.86 0.8598066 24.08 7.261237 0.09545856 9.03 24.08 3 -0.9999991 0.9999983 0.9999965 12 12 9.75 0.03046875 3.52 0 1.17 1.1755390 24.15 6.286508 0.11025949 9.03 24.15 3 -0.9996984 0.9993968 0.9987936 AUCLST AUCALL AUCIFO AUCIFOD AUCPEO AUCIFP AUCIFPD AUCPEP AUMCLST AUMCIFO AUMCPEO AUMCIFP AUMCPEP 1 148.92305 148.92305 216.61193 0.6769123 31.248917 216.61496 0.6769217 31.249876 1459.0711 4505.5348 67.61603 4505.6709 67.61701 2 91.52680 91.52680 100.17346 0.3130421 8.631687 100.06432 0.3127010 8.532030 706.5866 999.7723 29.32525 996.0716 29.06267 3 99.28650 99.28650 109.53597 0.3422999 9.357173 109.58572 0.3424554 9.398325 803.1859 1150.9648 30.21629 1152.6529 30.31850 4 106.79630 106.79630 118.37888 0.3699340 9.784331 118.44356 0.3701361 9.833594 901.0842 1303.2524 30.85881 1305.4981 30.97775 5 121.29440 121.29440 139.41978 0.4356868 13.000579 139.25463 0.4351707 12.897403 1017.1143 1667.7216 39.01174 1661.7937 38.79419 6 73.77555 73.77555 84.25442 0.2632951 12.437174 84.49670 0.2640522 12.688246 609.1524 978.4285 37.74176 986.9665 38.28034 7 90.75340 90.75340 103.77180 0.3242869 12.545221 103.89315 0.3246661 12.647366 782.4199 1245.0984 37.16000 1249.4111 37.37691 8 88.55995 88.55995 103.90669 0.3247084 14.769730 103.64305 0.3238845 14.552931 739.5346 1298.1158 43.03015 1288.5201 42.60589 9 86.32615 86.32615 99.90872 0.3122147 13.594978 99.86607 0.3120815 13.558076 705.2296 1201.7715 41.31750 1200.2124 41.24126 10 138.36810 138.36810 170.65206 0.5332877 18.918002 170.56791 0.5330247 18.878001 1278.1800 2473.9934 48.33535 2470.8765 48.27018 11 80.09360 80.09360 89.10274 0.2784461 10.110962 89.10072 0.2784397 10.108918 617.2422 928.5600 33.52694 928.4900 33.52193 12 119.97750 119.97750 130.58883 0.4080901 8.125757 130.63907 0.4082471 8.161087 977.8807 1330.3840 26.49636 1332.0528 26.58844 MRTEVLST MRTEVIFO MRTEVIFP VZFO VZFP CLFO CLFP AUC[0-12h] AUC[0-24h] 1 9.797483 20.800031 20.800368 30.48675 30.48632 1.477296 1.477276 91.73552 147.69459 2 7.719996 9.980411 9.954313 30.69044 30.72392 3.194459 3.197943 67.48030 91.24908 3 8.089578 10.507642 10.518276 28.51710 28.50415 2.921415 2.920088 70.17971 99.10481 4 8.437410 11.009163 11.022112 27.22596 27.21110 2.703185 2.701709 73.05115 105.99811 5 8.385501 11.961873 11.933490 26.49799 26.52942 2.295227 2.297949 84.61490 120.73101 6 8.256833 11.612785 11.680533 43.25973 43.13569 3.798020 3.787130 51.75887 73.91422 7 8.621383 11.998427 12.025924 34.90844 34.86767 3.083689 3.080088 62.09875 90.49567 8 8.350666 12.493092 12.432287 37.81051 37.90669 3.079686 3.087520 62.71486 88.40890 9 8.169363 12.028695 12.018220 38.84279 38.85938 3.202924 3.204292 60.12123 85.82985 10 9.237534 14.497296 14.486174 25.01554 25.02788 1.875160 1.876086 90.81742 139.08507 11 7.706511 10.421227 10.420679 37.62219 37.62304 3.591360 3.591441 58.53963 80.02431 12 8.150534 10.187579 10.196436 22.22429 22.21575 2.450439 2.449497 85.02136 119.79884</p>
<p>맨 마지막 파라미터로 AUC[0-12h], AUC[0-24h]가 추가되었음을 알 수 있다.</p>
<p>약동학 파라이터를 보고서 형식의 text 파일로 저장해보자.</p>
<p>우선 저장될 폴더를 확인해면,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">getwd</span>()</code></pre></div>
<pre><code>## [1] &quot;C:/Users/mdlhs/asancpt/ncarBook&quot;</code></pre>
<p>저장될 폴더를 변경하고자 한다면 setwd(“저장될 경로”) 이렇게 설정하면 된다. 위에서 사용한 NCA 명령어에 Report=“Text” 라는 옵션을 추가하면 된다. 먼저, Theophilline 자료의 약동학 파라미터 분석 결과는 아래와 같이 텍스트파일로 저장할 수 있다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#writeLines(NCA(Theoph, &quot;Subject&quot;, &quot;Time&quot;, &quot;conc&quot;, Dose=320, Report=&quot;Text&quot;), &quot;Theoph_Linear_CoreOutput.txt&quot;)</span></code></pre></div>
<p>저장된 파일 내용은 아래와 같다. NCA REPORT Subject=1</p>
<pre><code>                    NONCOMPARTMENTAL ANALYSIS REPORT
                   Package version 0.2.6 (2017-01-01)
                      R version 3.3.3 (2017-03-06)</code></pre>
<p>Date and Time: 2017-03-11 20:46:33 KST</p>
</div>
<div id="calculation-setting" class="section level2">
<h2><span class="header-section-number">4.2</span> Calculation Setting</h2>
<p>Drug Administration: Extravascular Observation count excluding trailing zero: 11 Dose at time 0: 320 AUC Calculation method: Linear-up Linear-down method Weighting for lambda z: Uniform (Ordinary Least Square, OLS) Lambda z selection criterion: Heighest adjusted R-squared value with precision=1e-4</p>
</div>
<div id="fitting-auc-aumc-result" class="section level2">
<h2><span class="header-section-number">4.3</span> Fitting, AUC, AUMC Result</h2>
</div>
<div id="time-conc.-pred.-residual-auc-aumc-weight" class="section level2">
<h2><span class="header-section-number">4.4</span> Time Conc. Pred. Residual AUC AUMC Weight</h2>
<pre><code> 0.0000       0.7400                           0.0000     0.0000            
 0.2500       2.8400                           0.4475     0.0888            
 0.5700       6.5700                           1.9531     0.8015            
 1.1200      10.5000                           6.6474     5.0654            
 2.0200       9.6600                          15.7194    19.1383            
 3.8200       8.5800                          32.1354    66.1982            
 5.1000       8.3600                          42.9769   114.4617            
 7.0300       7.4700                          58.2529   206.2815            
 9.0500 *     6.8900     6.8912 -1.228e-03    72.7565   322.2988     1.0000
12.1200 *     5.9400     5.9387 +1.324e-03    92.4505   528.5219     1.0000
24.3700 *     3.2800     3.2801 -1.465e-04   148.9231  1459.0711     1.0000</code></pre>
<p>*: Used for the calculation of Lambda z.</p>
</div>
<div id="calculated-values" class="section level2">
<h2><span class="header-section-number">4.5</span> Calculated Values</h2>
<p>CMAX Max Conc 10.5000 CMAXD Max Conc Norm by Dose 0.0328 TMAX Time of CMAX 1.1200 TLAG Time Until First Nonzero Conc 0.0000 CLST Last Nonzero Conc 3.2800 …</p>
<p>개인별 약동학 파라미터를 구하려면 아래와 같이 할 수 있다. IndiNCA를 사용하면 되며, NCA와의 차이점은 데이터셋과 subject 설정이 빠진다는 점이다.</p>
<blockquote>
<p>IndiNCA(Theoph[Theoph$Subject==1,“Time”], Theoph[Theoph$Subject==1, “conc”], Dose=320) CMAX CMAXD TMAX TLAG CLST CLSTP TLST LAMZHL LAMZ 10.5000000 0.0328125 1.1200000 0.0000000 3.2800000 3.2801465 24.3700000 14.3043776 0.0484570 LAMZLL LAMZUL LAMZNPT CORRXY R2 R2ADJ AUCLST AUCALL AUCIFO 9.0500000 24.3700000 3.0000000 -0.9999999 0.9999997 0.9999995 148.9230500 148.9230500 216.6119330 AUCIFOD AUCPEO AUCIFP AUCIFPD AUCPEP AUMCLST AUMCIFO AUMCPEO AUMCIFP 0.6769123 31.2489169 216.6149558 0.6769217 31.2498763 1459.0711035 4505.5348194 67.6160287 4505.6708646 AUMCPEP MRTEVLST MRTEVIFO MRTEVIFP VZFO VZFP CLFO CLFP 67.6170065 9.7974834 20.8000305 20.8003683 30.4867482 30.4863228 1.4772963 1.4772757</p>
</blockquote>
<p>개인별 약동학 파라미터를 보고서 형식의 text 파일로 저장해보자. Report 옵션을 추가하면 된다. Report=“Text” 를 추가해보자.</p>
<blockquote>
<p>IndiNCA(Theoph[Theoph$Subject==1,“Time”], Theoph[Theoph$Subject==1, “conc”], Dose=320, Report=“Text”) [1] &quot; NONCOMPARTMENTAL ANALYSIS REPORT&quot;<br />
[2] &quot; Package version 0.2.6 (2017-01-01)&quot;<br />
[3] &quot; R version 3.3.3 (2017-03-06)&quot;<br />
[4] “”<br />
[5] “Date and Time: 2017-03-11 21:12:40 KST”<br />
[6] “”<br />
[7] “Calculation Setting”<br />
[8] “——————-”<br />
[9] “Drug Administration: Extravascular”<br />
[10] “Observation count excluding trailing zero: 11”<br />
[11] “Dose at time 0: 320”<br />
[12] “AUC Calculation method: Linear-up Linear-down method”<br />
[13] “Weighting for lambda z: Uniform (Ordinary Least Square, OLS)”<br />
[14] “Lambda z selection criterion: Heighest adjusted R-squared value with precision=1e-4” [15] “”<br />
[16] “”<br />
[17] “Fitting, AUC, AUMC Result”<br />
[18] “————————-”<br />
[19] &quot; Time Conc. Pred. Residual AUC AUMC Weight&quot;<br />
[20] “——————————————————————————-”<br />
[21] &quot; 0.0000 0.7400 0.0000 0.0000 &quot;<br />
[22] &quot; 0.2500 2.8400 0.4475 0.0888 &quot;<br />
[23] &quot; 0.5700 6.5700 1.9531 0.8015 &quot;<br />
[24] &quot; 1.1200 10.5000 6.6474 5.0654 &quot;<br />
[25] &quot; 2.0200 9.6600 15.7194 19.1383 &quot;<br />
[26] &quot; 3.8200 8.5800 32.1354 66.1982 &quot;<br />
[27] &quot; 5.1000 8.3600 42.9769 114.4617 &quot;<br />
[28] &quot; 7.0300 7.4700 58.2529 206.2815 &quot;<br />
[29] &quot; 9.0500 * 6.8900 6.8912 -1.228e-03 72.7565 322.2988 1.0000&quot;<br />
[30] &quot; 12.1200 * 5.9400 5.9387 +1.324e-03 92.4505 528.5219 1.0000&quot;<br />
[31] &quot; 24.3700 * 3.2800 3.2801 -1.465e-04 148.9231 1459.0711 1.0000&quot;<br />
[32] “”<br />
[33] “*: Used for the calculation of Lambda z.&quot;<br />
[34] “”<br />
[35] “”<br />
[36] “Calculated Values”<br />
[37] “—————–”<br />
[38] “CMAX Max Conc 10.5000”<br />
[39] “CMAXD Max Conc Norm by Dose 0.0328”<br />
[40] “TMAX Time of CMAX 1.1200”<br />
[41] “TLAG Time Until First Nonzero Conc 0.0000”<br />
[42] “CLST Last Nonzero Conc 3.2800”<br />
[43] “CLSTP Last Nonzero Conc Pred 3.2801”<br />
[44] “TLST Time of Last Nonzero Conc 24.3700”<br />
[45] “LAMZHL Half-Life Lambda z 14.3044”<br />
[46] “LAMZ Lambda z 0.0485”<br />
[47] “LAMZLL Lambda z Lower Limit 9.0500”<br />
[48] “LAMZUL Lambda z Upper Limit 24.3700”<br />
[49] “LAMZNPT Number of Points for Lambda z 3”<br />
[50] “CORRXY Correlation Between TimeX and Log ConcY -1.0000”<br />
[51] “R2 R Squared 1.0000”<br />
[52] “R2ADJ R Squared Adjusted 1.0000”<br />
[53] “AUCLST AUC to Last Nonzero Conc 148.9231”<br />
[54] “AUCALL AUC All 148.9231”<br />
[55] “AUCIFO AUC Infinity Obs 216.6119”<br />
[56] “AUCIFOD AUC Infinity Obs Norm by Dose 0.6769”<br />
[57] “AUCPEO AUC %Extrapolation Obs 31.2489”<br />
[58] “AUCIFP AUC Infinity Pred 216.6150”<br />
[59] “AUCIFPD AUC Infinity Pred Norm by Dose 0.6769”<br />
[60] “AUCPEP AUC %Extrapolation Pred 31.2499”<br />
[61] “AUMCLST AUMC to Last Nonzero Conc 1459.0711”<br />
[62] “AUMCIFO AUMC Infinity Obs 4505.5348”<br />
[63] “AUMCPEO AUMC %Extrapolation Obs 67.6160”<br />
[64] “AUMCIFP AUMC Infinity Pred 4505.6709”<br />
[65] “AUMCPEP AUMC % Extrapolation Pred 67.6170”<br />
[66] “MRTEVLST MRT Extravasc to Last Nonzero Conc 9.7975”<br />
[67] “MRTEVIFO MRT Extravasc Infinity Obs 20.8000”<br />
[68] “MRTEVIFP MRT Extravasc Infinity Pred 20.8004”<br />
[69] “VZFO Vz Obs by F 30.4867”<br />
[70] “VZFP Vz Pred by F 30.4863”<br />
[71] “CLFO Total CL Obs by F 1.4773”<br />
[72] “CLFP Total CL Pred by F 1.4773”</p>
</blockquote>
<p>개인별 일부 구간의 AUC를 구하는 방법은 아래와 같다. 예를 들어 0~12시간까지의 AUC, 0~24시간까지의 AUC를 구하고자 한다면 다음과 같이 하면 된다.</p>
<blockquote>
<p>iAUC = data.frame(Name=c(“AUC[0-12h]”,“AUC[0-24h]”), Start=c(0,0), End=c(12,24)) ; iAUC</p>
</blockquote>
<pre><code>    Name Start End</code></pre>
<p>1 AUC[0-12h] 0 12 2 AUC[0-24h] 0 24</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">IntAUC</code></pre></div>
<pre><code>## function (x, y, t1, t2, Res, down = &quot;Linear&quot;) 
## {
##     n = length(x)
##     if (n != length(y) | !is.numeric(x) | !is.numeric(y)) 
##         stop(&quot;Bad Input!&quot;)
##     if (t1 &gt; Res[&quot;TLST&quot;]) 
##         stop(&quot;Start time of interval AUC is after Tlast.&quot;)
##     tL = Res[&quot;TLST&quot;]
##     if (t2 &gt; tL &amp; is.na(Res[&quot;LAMZ&quot;])) 
##         return(NA)
##     newSeries = Interpol(x, y, t1, Res[&quot;LAMZ&quot;], Res[&quot;b0&quot;], down = down)
##     newSeries = Interpol(newSeries[[1]], newSeries[[2]], t2, 
##         Res[&quot;LAMZ&quot;], Res[&quot;b0&quot;], down = down)
##     x = newSeries[[1]]
##     y = newSeries[[2]]
##     if (down == &quot;Linear&quot;) {
##         if (t2 &lt;= tL) {
##             ResIntAUC = LinAUC(x[x &gt;= t1 &amp; x &lt;= t2], y[x &gt;= t1 &amp; 
##                 x &lt;= t2])[[1]]
##         }
##         else {
##             ResIntAUC = LinAUC(x[x &gt;= t1 &amp; x &lt;= tL], y[x &gt;= t1 &amp; 
##                 x &lt;= tL])[[1]] + LogAUC(x[x &gt;= tL &amp; x &lt;= t2], 
##                 y[x &gt;= tL &amp; x &lt;= t2])[[1]]
##         }
##     }
##     else if (down == &quot;Log&quot;) {
##         ResIntAUC = LogAUC(x[x &gt;= t1 &amp; x &lt;= t2], y[x &gt;= t1 &amp; 
##             x &lt;= t2])[[1]]
##     }
##     else stop(&quot;Unknown down method!&quot;)
##     return(ResIntAUC)
## }
## &lt;environment: namespace:NonCompart&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">IntAUC</span>(Theoph[Theoph<span class="op">$</span>Subject<span class="op">==</span><span class="dv">1</span>,<span class="st">&quot;Time&quot;</span>], Theoph[Theoph<span class="op">$</span>Subject<span class="op">==</span><span class="dv">1</span>, <span class="st">&quot;conc&quot;</span>], <span class="dt">Dose=</span><span class="dv">320</span>, <span class="dt">iAUC=</span>iAUC)</code></pre></div>
<pre><code>## Error in IntAUC(Theoph[Theoph$Subject == 1, &quot;Time&quot;], Theoph[Theoph$Subject == : unused arguments (Dose = 320, iAUC = iAUC)</code></pre>
<pre><code>    CMAX        CMAXD         TMAX         TLAG         CLST        CLSTP         TLST       LAMZHL         LAMZ </code></pre>
<p>10.5000000 0.0328125 1.1200000 0.0000000 3.2800000 3.2801465 24.3700000 14.3043776 0.0484570 LAMZLL LAMZUL LAMZNPT CORRXY R2 R2ADJ AUCLST AUCALL AUCIFO 9.0500000 24.3700000 3.0000000 -0.9999999 0.9999997 0.9999995 148.9230500 148.9230500 216.6119330 AUCIFOD AUCPEO AUCIFP AUCIFPD AUCPEP AUMCLST AUMCIFO AUMCPEO AUMCIFP 0.6769123 31.2489169 216.6149558 0.6769217 31.2498763 1459.0711035 4505.5348194 67.6160287 4505.6708646 AUMCPEP MRTEVLST MRTEVIFO MRTEVIFP VZFO VZFP CLFO CLFP AUC[0-12h] 67.6170065 9.7974834 20.8000305 20.8003683 30.4867482 30.4863228 1.4772963 1.4772757 91.7355220 AUC[0-24h] 147.6945866</p>
<p>전반적으로 초보자도 어렵지 않게 사용할 수 있다. 역시 배균섭 교수님 이시다. 약동학 Plot 도 자동으로 그려주면 더 좋을텐데..ㅎㅎ</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="nca-r-.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="DetailsNCA.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/asancpt/ncar/edit/master/bookdown/ms-kim.Rmd",
"text": "Edit"
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
